;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	mouse-drag-secondary
	org-ctrl-c-ctrl-c
	org-force-self-insert
	org-self-insert-command
	smex
	))

(setq mc/cmds-to-run-once
      '(
	mouse-set-region
	))
